AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: >
  SearchAPI-v3

  SearchAPI stack on lambda, powered by SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 10240
    Architectures:
      - x86_64

Resources:

  SearchApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: !Sub 'SAM deployment for stack "${AWS::StackName}"'
      PackageType: Image
      ImageConfig:
        EntryPoint: [ "/lambda-entrypoint.sh" ]
        Command: [ "SearchAPI.main.lambda_handler" ]        
      Events:
        Root:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
                Path: /
                Method: ANY
        NonRoot:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
                Path: /{proxy+}
                Method: ANY
      Environment:
        Variables:
          LOCAL_RUN: "FALSE"
    Metadata:
      DockerTag: searchapi-v3
      DockerContext: ./
      Dockerfile: Dockerfile


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SearchApiUrl:
    Description: API Gateway endpoint URL for Prod stage for lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
