name: SearchAPI deploy action (prod)

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: edc-prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/search-api-composite
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          vpc-id: ${{ secrets.VPC_ID }}
          subnet-ids: ${{ secrets.SUBNET_IDS }}
          security-group: ${{ secrets.SECURITY_GROUP }}
