name: SearchAPI deploy action (test)

on:
    push:
      branches:
        - test

jobs:
  deploy-edc-test:
    runs-on: ubuntu-latest
    environment: edc-test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/search-api-composite
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          vpc-id: ${{ secrets.VPC_ID }}
          subnet-ids: ${{ secrets.SUBNET_IDS }}
          security-group: ${{ secrets.SECURITY_GROUP }}

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/search-api-composite
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
