name: SearchAPI pytest suite
permissions:
  contents: read
on:
    pull_request:
      branches:
        - test
        - prod
      types:
        - opened
        - reopened
        - synchronize
      paths:
        - 'src/**.py'
        # - 'cdk/**.py'


jobs:
    run-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
    
        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
            python -m pip install .
        
        - name: run tests
          shell: bash
          run: |
            pytest -n auto tests/yml_tests/ \
            --df bugs --df prod_only --cov \
            --reruns 3 --reruns-delay 10 --only-rerun CMR_TIMEOUT \
            --cov-branch --cov-report=xml
  
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: false
            files: ./coverage.xml
            flags: unittests
            name: asf_admin searchAPI-v3 pytest
            verbose: true

    # Deploy Staging
    deploy-edc-test-staging:
      needs: [run-tests]
      runs-on: ubuntu-latest
      environment: edc-test
      permissions:
        id-token: write
        contents: read

      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: build
          uses: ./.github/workflows/search-api-composite
          with:
            aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
            vpc-id: ${{ secrets.VPC_ID }}
            subnet-ids: ${{ secrets.SUBNET_IDS }}
            security-group: ${{ secrets.SECURITY_GROUP }}
            staging: true

    run-tests-edc-staging:
      needs: [deploy-edc-test-staging]
      runs-on: ubuntu-latest
      environment: edc-test
      permissions:
        id-token: write
        contents: read
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Configure AWS OIDC credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/SearchAPIActionsOIDCRole
            aws-region: us-west-2
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
    
        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
            python -m pip install .
        
        - name: run tests
          shell: bash
          run: |
            pytest tests/yml_tests/test_stack.py \
            --reruns 3 --reruns-delay 10

    deploy-test-staging:
      needs: [run-tests]
      runs-on: ubuntu-latest
      environment: test
      permissions:
        id-token: write
        contents: read
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: build
          uses: ./.github/workflows/search-api-composite
          with:
            aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
            staging: true
    
    run-tests-staging:
      needs: [deploy-test-staging]
      runs-on: ubuntu-latest
      environment: test
      permissions:
        id-token: write
        contents: read
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Configure AWS OIDC credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/SearchAPIActionsOIDCRole
            aws-region: us-west-2
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
    
        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
            python -m pip install .
        
        - name: run tests
          shell: bash
          run: |
            pytest tests/yml_tests/test_stack.py \
            --reruns 3 --reruns-delay 10
