name: SearchAPI pytest suite
permissions:
  contents: read
on:
    pull_request:
      branches:
        - test
      types:
        - opened
        - reopened
        - synchronize
      paths:
        - '**.py'


jobs:
    run-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
    
        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
            python -m pip install .
        
        - name: run tests
          shell: bash
          run: "pytest -n auto tests/yml_tests/ --df bugs --df prod_only"
  